language: c
env:
- TOOLCHAIN_DIR=$HOME/qkthings_local/toolchain
install:
- sudo apt-get install build-essential python
before_script:
- git clone https://github.com/qkthings/qkthings.git
- cd qkthigs/dev/python
- sudo python setup.py install
- sudo python qkthings/toolman.py -t arduino -r $TOOLCHAIN_DIR --dist=linux
- sudo python qkthings/toolman.py -t efm32 -r $TOOLCHAIN_DIR --dist=linux
- git clone https://github.com/qkthings/qkperipheral.git
- git clone https://github.com/qkthings/qkprogram.git
- git clone https://github.com/qkthings/qkdsp.git
- cd $TRAVIS_BUILD_DIR
script:
- python deploy.py